##### Задача 1
Создать одномерный массив Numpy под названием a из 12 последовательных целых чисел чисел от 12 до 24 невключительно

In [467]:
import numpy as np
import pandas as pd

In [468]:
a = np.arange(12,24)
a

array([12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23])

##### Задача 2

Создать 5 двумерных массивов разной формы из массива a. Не использовать в аргументах метода reshape число -1.

In [469]:
a_1 = a.reshape(2,6)
a_2 = a.reshape(4,3)
a_3 = a.reshape(3,4)
a_4 = a.reshape(6,2)
a_5 = a.reshape(1,12)
np.shape(a_5)

(1, 12)

##### Задача 3

Создать 5 двумерных массивов разной формы из массива a. Использовать в аргументах метода reshape число -1 (в трех примерах - для обозначения числа столбцов, в двух - для строк).

In [470]:
a_1 = a.reshape (-1, 12)
a_2 = a.reshape (-1, 6)
a_3 = a.reshape (-1, 3)
a_4 = a.reshape (2, -1)
a_5 = a.reshape(4, -1)
a_5

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20],
       [21, 22, 23]])

##### Задача 4

Можно ли массив Numpy, состоящий из одного столбца и 12 строк, назвать одномерным?

In [471]:
print(a)
print(a_1)
print(a.ndim)
print(a_1.ndim)
print('Нельзя, потому, что массив a_1 содержит 1 элемент, который является массивом')

[12 13 14 15 16 17 18 19 20 21 22 23]
[[12 13 14 15 16 17 18 19 20 21 22 23]]
1
2
Нельзя, потому, что массив a_1 содержит 1 элемент, который является массивом


##### Задача 5

Создать массив из 3 строк и 4 столбцов, состоящий из случайных чисел с плавающей запятой из нормального распределения со средним, равным 0 и среднеквадратичным отклонением, равным 1.0. Получить из этого массива одномерный массив с таким же атрибутом size, как и исходный массив.


In [472]:
a = np.random.randn(3, 4)

a_shaped = np.reshape(a, 12)
print(np.size(a))
print(np.size(a_shaped))

12
12


##### Задача 6

Создать массив a, состоящий из целых чисел, убывающих от 20 до 0 невключительно с интервалом 2.

In [473]:
a = np.arange(20, 0, -2)
a

array([20, 18, 16, 14, 12, 10,  8,  6,  4,  2])

##### Задача 7

Создать массив b, состоящий из 1 строки и 10 столбцов: целых чисел, убывающих от 20 до 1 невключительно с интервалом 2. В чем разница между массивами a и b?

In [474]:
b = np.reshape(a, (1, 10))
print('Массив a - одномерный,b - двумерный')

Массив a - одномерный,b - двумерный


##### Задача 8

Вертикально соединить массивы a и b. a - двумерный массив из нулей, число строк которого больше 1 и на 1 меньше, чем число строк двумерного массива b, состоящего из единиц. Итоговый массив v должен иметь атрибут size, равный 10.

In [475]:
b = np.ones((2, 2))
a = np.zeros(((np.shape(b)[0]) + 1, 2))

c = np.vstack((a, b))

##### Задача 9

Создать одномерный массив а, состоящий из последовательности целых чисел от 0 до 12. Поменять форму этого массива, чтобы получилась матрица A (двумерный массив Numpy), состоящая из 4 строк и 3 столбцов. Получить матрицу At путем транспонирования матрицы A. Получить матрицу B, умножив матрицу A на матрицу At с помощью матричного умножения. Какой размер имеет матрица B? Получится ли вычислить обратную матрицу для матрицы B и почему?

In [476]:
a = np.arange(12)
a = a.reshape(4, 3)
At = a.T
B = np.dot(a, At)
print(np.linalg.det(B))
print('Если умножать матрицу размера 4,k на k,4 то получиться 4,4 матрица.')
print('Не получится потому, что определитель матрицы b равен нулю.')

0.0
Если умножать матрицу размера 4,k на k,4 то получиться 4,4 матрица.
Не получится потому, что определитель матрицы b равен нулю.


##### Задача 10

Инициализируйте генератор случайных чисел с помощью объекта seed, равного 42.



In [477]:
a = np.random.seed(42)
np.random.rand(3, 4)

array([[0.37454012, 0.95071431, 0.73199394, 0.59865848],
       [0.15601864, 0.15599452, 0.05808361, 0.86617615],
       [0.60111501, 0.70807258, 0.02058449, 0.96990985]])

##### Задача 11

Создайте одномерный массив c, составленный из последовательности 16-ти случайных равномерно распределенных целых чисел от 0 до 16 невключительно

In [478]:
C = np.random.randint(0, 16, 16)

c

array([[0., 0.],
       [0., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.]])

##### Задача 12

Поменяйте его форму так, чтобы получилась квадратная матрица C. Получите матрицу D, поэлементно прибавив матрицу B из предыдущего вопроса к матрице C, умноженной на 10. Вычислите определитель, ранг и обратную матрицу D_inv для D.


In [479]:
C = np.reshape(C, (4, 4))

D = B + (C * 10)
print(np.linalg.det(D))
print(np.linalg.matrix_rank(D))
D_inv = np.linalg.inv(D)
print(D_inv)

-31734200.000000056
4
[[-0.02273446  0.03132204 -0.03241865  0.01964316]
 [ 0.02434471 -0.02021478  0.00035671  0.00329676]
 [ 0.00561098 -0.0128423   0.06299513 -0.04871464]
 [-0.00716136  0.00586623 -0.02194919  0.01958266]]


##### Задача 13

Приравняйте к нулю отрицательные числа в матрице D_inv, а положительные - к единице. Убедитесь, что в матрице D_inv остались только нули и единицы. С помощью функции numpy.where, используя матрицу D_inv в качестве маски, а матрицы B и C - в качестве источников данных, получите матрицу E размером 4x4.  Элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 1, должны быть равны соответствующему элементу матрицы B, а элементы матрицы E, для которых соответствующий элемент матрицы D_inv равен 0, должны быть равны соответствующему элементу матрицы C.


In [491]:
np.place(D_inv, D_inv > 0, 1)
np.place(D_inv, D_inv < 0, 0)
D_inv
print(B)
print(C)
print(D_inv)
E = np.where(D_inv, B, C)
print(E)


[[  5  14  23  32]
 [ 14  50  86 122]
 [ 23  86 149 212]
 [ 32 122 212 302]]
[[11 13  5  1]
 [15 11  4  0]
 [11  9  5 12]
 [11  8  0 10]]
[[0. 1. 0. 1.]
 [1. 0. 1. 1.]
 [1. 0. 1. 0.]
 [0. 1. 0. 1.]]
[[ 11  14   5  32]
 [ 14  11  86 122]
 [ 23   9 149  12]
 [ 11 122   0 302]]
